# Generated by Django 6.0.7 on 2026-08-03 03:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0013_itemfila_turno_a_ticket'),
        ('instituciones', '0008_cama_estadiacama'),
        ('registros', '0004_alter_historiaclinica_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('instituciones', models.ManyToManyField(blank=True, related_name='redes', to='instituciones.institucion')),
            ],
            options={
                'verbose_name': 'red de establecimientos',
                'verbose_name_plural': 'redes de establecimientos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('en_camino', 'En camino'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='solicitado', max_length=20)),
                ('motivo', models.CharField(choices=[('complejidad', 'Mayor complejidad'), ('especialidad', 'Especialidad no disponible'), ('cama', 'Falta de cama'), ('estudio', 'Estudio no disponible'), ('cercania', 'Cercanía al domicilio'), ('otro', 'Otro')], default='complejidad', max_length=20)),
                ('detalle', models.TextField(blank=True, help_text='Resumen clínico para quien recibe.')),
                ('urgente', models.BooleanField(default=False)),
                ('respuesta', models.TextField(blank=True, verbose_name='respuesta del destino')),
                ('solicitado_at', models.DateTimeField(auto_now_add=True)),
                ('resuelto_at', models.DateTimeField(blank=True, null=True)),
                ('salida_at', models.DateTimeField(blank=True, null=True)),
                ('llegada_at', models.DateTimeField(blank=True, null=True)),
                ('movil', models.CharField(blank=True, max_length=80, verbose_name='móvil / ambulancia')),
                ('area_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_recibidos', to='instituciones.area')),
                ('caso_destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslado_recibido', to='casos.caso')),
                ('caso_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados', to='casos.caso')),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados', to='registros.ciudadano')),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_recibidos', to='instituciones.institucion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traslados_enviados', to='instituciones.institucion')),
                ('red', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados', to='red.red')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_resueltos', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_solicitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'traslado',
                'verbose_name_plural': 'traslados',
                'ordering': ['-urgente', '-solicitado_at'],
                'indexes': [models.Index(fields=['destino', 'estado'], name='red_traslad_destino_990e2b_idx'), models.Index(fields=['origen', 'estado'], name='red_traslad_origen__6193f1_idx')],
            },
        ),
    ]
