# Generated by Django 6.1 on 2026-08-15 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('red', '0001_initial'),
        ('registros', '0006_consentimientodatos'),
    ]

    operations = [
        migrations.AddField(
            model_name='traslado',
            name='ciudadano_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='traslados_como_destino', to='registros.ciudadano'),
        ),
        migrations.AlterField(
            model_name='traslado',
            name='estado',
            field=models.CharField(choices=[('solicitado', 'Solicitado'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('en_camino', 'En camino'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado'), ('fallido', 'No llegó')], default='solicitado', max_length=20),
        ),
    ]
