# Generated by Django 6.0.6 on 2026-06-23 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('formularios', '0001_initial'),
        ('instituciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos', to='instituciones.area')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flujos', to='instituciones.institucion')),
            ],
            options={
                'verbose_name': 'flujo',
                'verbose_name_plural': 'flujos',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='VersionFlujo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='1, 2, 3… mostrado como v1, v2, v3')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('publicada', 'Publicada'), ('reemplazada', 'Reemplazada'), ('archivada', 'Archivada')], default='borrador', max_length=20)),
                ('nota', models.TextField(blank=True, verbose_name='nota de cambios')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_creadas', to=settings.AUTH_USER_MODEL)),
                ('flujo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='flujos.flujo')),
            ],
            options={
                'verbose_name': 'versión de flujo',
                'verbose_name_plural': 'versiones de flujo',
                'ordering': ['flujo', '-numero'],
                'unique_together': {('flujo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inicio', 'Inicio'), ('form', 'Formulario'), ('decision', 'Decisión'), ('accion', 'Acción'), ('atencion', 'Atención'), ('derivar', 'Derivar'), ('espera', 'Espera de fila'), ('tiempo', 'Espera por tiempo'), ('estado', 'Estado'), ('fin', 'Fin')], max_length=20)),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('formulario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodos', to='formularios.formulario')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='flujos.versionflujo')),
            ],
            options={
                'verbose_name': 'nodo',
                'verbose_name_plural': 'nodos',
            },
        ),
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.CharField(blank=True, max_length=120)),
                ('condicion', models.JSONField(blank=True, default=dict)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='flujos.nodo')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salidas', to='flujos.nodo')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conexiones', to='flujos.versionflujo')),
            ],
            options={
                'verbose_name': 'conexión',
                'verbose_name_plural': 'conexiones',
            },
        ),
    ]
