# Generated by Django 6.0.6 on 2026-06-24 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujos', '0001_initial'),
        ('instituciones', '0004_institucion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='flujo',
            name='subarea',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flujos', to='instituciones.subarea'),
        ),
    ]
