# Generated by Django 6.0.6 on 2026-06-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujos', '0002_flujo_subarea'),
        ('instituciones', '0005_grupo'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='grupos',
            field=models.ManyToManyField(blank=True, related_name='nodos', to='instituciones.grupo'),
        ),
    ]
