# Generated by Django 6.0.7 on 2026-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujos', '0004_nodo_pantalla_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodo',
            name='tipo',
            field=models.CharField(choices=[('inicio', 'Inicio'), ('form', 'Formulario'), ('decision', 'Decisión'), ('accion', 'Acción'), ('atencion', 'Atención'), ('derivar', 'Derivar'), ('espera', 'Espera de fila'), ('tiempo', 'Espera por tiempo'), ('estado', 'Estado'), ('notificar', 'Notificación'), ('integracion', 'Integración'), ('fin', 'Fin')], max_length=20),
        ),
    ]
