# Generated by Django 6.0.7 on 2026-08-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flujos', '0005_alter_nodo_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conexion',
            options={'ordering': ['id'], 'verbose_name': 'conexión', 'verbose_name_plural': 'conexiones'},
        ),
        migrations.AlterModelOptions(
            name='nodo',
            options={'ordering': ['id'], 'verbose_name': 'nodo', 'verbose_name_plural': 'nodos'},
        ),
    ]
