# Generated by Django 5.2.15 on 2026-09-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flujos', '0007_alter_nodo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='versionflujo',
            name='tipo_circuito',
            field=models.CharField(choices=[('no_definido', 'No definido'), ('guardia', 'Guardia'), ('programado', 'Programado')], default='no_definido', max_length=20),
        ),
    ]
