# Generated by Django 6.0.7 on 2026-08-02 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0013_itemfila_turno_a_ticket'),
        ('flujos', '0007_alter_nodo_tipo'),
        ('instituciones', '0008_cama_estadiacama'),
        ('registros', '0004_alter_historiaclinica_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('profesional', 'Profesional'), ('recurso', 'Recurso')], default='profesional', max_length=20)),
                ('nombre', models.CharField(help_text='Ej.: «Dra. Suárez» o «Tomógrafo»', max_length=150)),
                ('duracion_min', models.PositiveIntegerField(default=20, help_text='Duración por defecto; cada franja puede pisarla.', verbose_name='duración del turno (minutos)')),
                ('sobreturnos_max', models.PositiveIntegerField(default=2, verbose_name='sobreturnos por franja')),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='instituciones.area')),
                ('flujo', models.ForeignKey(blank=True, help_text='Flujo que se abre cuando el paciente se presenta al turno.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas', to='flujos.flujo')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='instituciones.institucion')),
                ('profesional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agenda',
                'verbose_name_plural': 'agendas',
                'ordering': ['nombre'],
                'unique_together': {('institucion', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Bloqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloqueos', to='agenda.agenda')),
            ],
            options={
                'verbose_name': 'bloqueo de agenda',
                'verbose_name_plural': 'bloqueos de agenda',
                'ordering': ['desde'],
            },
        ),
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.PositiveSmallIntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miércoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='día')),
                ('desde', models.TimeField(verbose_name='desde')),
                ('hasta', models.TimeField(verbose_name='hasta')),
                ('duracion_min', models.PositiveIntegerField(blank=True, help_text='Si se deja vacío, usa la de la agenda.', null=True, verbose_name='duración (minutos)')),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to='agenda.agenda')),
            ],
            options={
                'verbose_name': 'disponibilidad',
                'verbose_name_plural': 'disponibilidades',
                'ordering': ['dia_semana', 'desde'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio', models.DateTimeField()),
                ('duracion_min', models.PositiveIntegerField(default=20)),
                ('estado', models.CharField(choices=[('reservado', 'Reservado'), ('confirmado', 'Confirmado'), ('presente', 'Se presentó'), ('ausente', 'No se presentó'), ('cancelado', 'Cancelado')], default='reservado', max_length=20)),
                ('sobreturno', models.BooleanField(default=False)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('origen', models.CharField(choices=[('mostrador', 'Mostrador'), ('telefono', 'Teléfono'), ('derivacion', 'Derivación')], default='mostrador', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('recordado_at', models.DateTimeField(blank=True, null=True)),
                ('cancelado_at', models.DateTimeField(blank=True, null=True)),
                ('agenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='agenda.agenda')),
                ('caso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turno', to='casos.caso')),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos', to='registros.ciudadano')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_dados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ['inicio', 'id'],
                'indexes': [models.Index(fields=['agenda', 'inicio'], name='agenda_turn_agenda__2d312e_idx')],
            },
        ),
    ]
