# Generated by Django 6.1 on 2026-08-15 09:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
        ('casos', '0013_itemfila_turno_a_ticket'),
        ('registros', '0006_consentimientodatos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='resuelto_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='turno',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_resueltos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(condition=models.Q(('sobreturno', False), models.Q(('estado', 'cancelado'), _negated=True)), fields=('agenda', 'inicio'), name='un_titular_por_horario'),
        ),
    ]
