# Generated by Django 6.1 on 2026-08-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_turno_resuelto_at_turno_resuelto_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='enlace_virtual',
            field=models.URLField(blank=True, help_text='Sala de videollamada de esta agenda. Se copia a cada turno virtual.', verbose_name='enlace de la sala'),
        ),
        migrations.AddField(
            model_name='agenda',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('mixta', 'Presencial o virtual')], default='presencial', help_text='Si es mixta, se elige al dar cada turno.', max_length=20, verbose_name='modalidad'),
        ),
        migrations.AddField(
            model_name='turno',
            name='enlace',
            field=models.URLField(blank=True, verbose_name='enlace de la videollamada'),
        ),
        migrations.AddField(
            model_name='turno',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], default='presencial', max_length=20, verbose_name='modalidad'),
        ),
    ]
