# Generated by Django 6.1 on 2026-08-18 16:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_agenda_enlace_virtual_agenda_modalidad_turno_enlace_and_more'),
        ('casos', '0013_itemfila_turno_a_ticket'),
        ('registros', '0008_normalizar_documentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turno',
            name='un_titular_por_horario',
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='cupos',
            field=models.PositiveIntegerField(default=1, help_text='1 es lo normal (un consultorio). Más de 1 para puestos en paralelo.', verbose_name='personas por horario'),
        ),
        migrations.AddField(
            model_name='disponibilidad',
            name='sobreturnos_max',
            field=models.PositiveIntegerField(blank=True, help_text='Si se deja vacío, usa los de la agenda.', null=True, verbose_name='sobreturnos por horario'),
        ),
        migrations.AddField(
            model_name='turno',
            name='posicion',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(condition=models.Q(('sobreturno', False), models.Q(('estado', 'cancelado'), _negated=True)), fields=('agenda', 'inicio', 'posicion'), name='un_turno_por_cupo'),
        ),
    ]
