# Generated by Django 5.2.15 on 2026-09-24 14:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_remove_turno_un_titular_por_horario_and_more'),
        ('casos', '0014_caso_espera_autorizacion'),
        ('registros', '0010_sello_version'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='turno',
            name='un_turno_por_cupo',
        ),
        migrations.AddField(
            model_name='turno',
            name='motivo_registro',
            field=models.CharField(blank=True, max_length=300, verbose_name='motivo del registro retrospectivo'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='estado',
            field=models.CharField(choices=[('reservado', 'Reservado'), ('confirmado', 'Confirmado'), ('presente', 'Se presentó'), ('ausente', 'No se presentó'), ('cancelado', 'Cancelado'), ('realizado', 'Atención pasada registrada')], default='reservado', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='turno',
            constraint=models.UniqueConstraint(condition=models.Q(('sobreturno', False), models.Q(('estado__in', ['cancelado', 'realizado']), _negated=True)), fields=('agenda', 'inicio', 'posicion'), name='un_turno_por_cupo'),
        ),
    ]
