# Generated by Django 5.2.15 on 2026-09-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_remove_turno_un_turno_por_cupo_turno_motivo_registro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='clave_operacion',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='clave de operación retrospectiva'),
        ),
    ]
