# Generated by Django 5.2.15 on 2026-10-08 15:39

from django.db import migrations, models


def turnos_previos_por_el_sistema(apps, schema_editor):
    """Antes del portal todo se confirmaba o cancelaba desde el sistema.

    No se usa `recordado_at`: también lo marca `recordar_turnos` al listar un
    turno, sin que nadie lo confirme. Un turno que pasó de confirmado a otro
    estado queda sin vía: no hay de dónde saberlo.
    """
    Turno = apps.get_model("agenda", "Turno")
    Turno.objects.filter(estado="confirmado").update(confirmado_via="sistema")
    Turno.objects.filter(cancelado_at__isnull=False).update(cancelado_via="sistema")


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_turno_clave_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='cancelado_via',
            field=models.CharField(blank=True, choices=[('sistema', 'Sistema'), ('portal', 'Portal del paciente')], max_length=10),
        ),
        migrations.AddField(
            model_name='turno',
            name='confirmado_via',
            field=models.CharField(blank=True, choices=[('sistema', 'Sistema'), ('portal', 'Portal del paciente')], max_length=10),
        ),
        migrations.RunPython(turnos_previos_por_el_sistema, migrations.RunPython.noop),
    ]
