# Generated by Django 6.0.6 on 2026-06-23 23:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formularios', to='instituciones.area')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formularios', to='instituciones.institucion')),
            ],
            options={
                'verbose_name': 'formulario',
                'verbose_name_plural': 'formularios',
                'ordering': ['titulo'],
            },
        ),
        migrations.CreateModel(
            name='Campo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('texto_corto', 'Texto corto'), ('texto_largo', 'Texto largo'), ('fecha', 'Fecha'), ('seleccion_unica', 'Selección única'), ('archivo', 'Archivo adjunto')], max_length=20)),
                ('requerido', models.BooleanField(default=False)),
                ('ayuda', models.CharField(blank=True, max_length=255, verbose_name='texto de ayuda')),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('origen', models.CharField(blank=True, choices=[('historia_clinica', 'Historia clínica'), ('legajo_ciudadano', 'Legajo ciudadano')], max_length=20)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos', to='formularios.formulario')),
            ],
            options={
                'verbose_name': 'campo',
                'verbose_name_plural': 'campos',
                'ordering': ['formulario', 'orden'],
            },
        ),
    ]
