# Generated by Django 6.1 on 2026-08-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campo',
            name='maximo',
            field=models.FloatField(blank=True, null=True, verbose_name='máximo'),
        ),
        migrations.AddField(
            model_name='campo',
            name='minimo',
            field=models.FloatField(blank=True, null=True, verbose_name='mínimo'),
        ),
        migrations.AddField(
            model_name='campo',
            name='unidad',
            field=models.CharField(blank=True, max_length=20, verbose_name='unidad'),
        ),
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('texto_corto', 'Texto corto'), ('texto_largo', 'Texto largo'), ('numero', 'Número'), ('fecha', 'Fecha'), ('seleccion_unica', 'Selección única'), ('archivo', 'Archivo adjunto')], max_length=20),
        ),
    ]
