# Generated by Django 5.2.15 on 2026-09-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularios', '0002_campo_maximo_campo_minimo_campo_unidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campo',
            name='tipo',
            field=models.CharField(choices=[('texto_corto', 'Texto corto'), ('texto_largo', 'Texto largo'), ('numero', 'Número'), ('fecha', 'Fecha'), ('seleccion_unica', 'Selección única'), ('archivo', 'Archivo adjunto'), ('booleano', 'Sí/No'), ('seleccion_multiple', 'Selección múltiple'), ('hora', 'Hora'), ('email', 'Correo electrónico'), ('telefono', 'Teléfono')], max_length=20),
        ),
    ]
