# Generated by Django 6.0.6 on 2026-06-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='tipo',
            field=models.CharField(blank=True, help_text='Hospital general, Centro de salud, Organismo…', max_length=120, verbose_name='tipo'),
        ),
    ]
