# Generated by Django 6.0.6 on 2026-06-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0002_institucion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='descripción'),
        ),
        migrations.AddField(
            model_name='area',
            name='responsable',
            field=models.CharField(blank=True, max_length=150, verbose_name='responsable / jefe'),
        ),
    ]
