# Generated by Django 6.0.6 on 2026-06-24 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0003_area_descripcion_area_responsable'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('en_alta', 'En alta'), ('inactiva', 'Inactiva')], default='activa', max_length=20),
        ),
    ]
