# Generated by Django 6.0.6 on 2026-06-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0005_grupo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej.: «Box 1», «Consultorio A»', max_length=80)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='instituciones.area')),
            ],
            options={
                'verbose_name': 'box',
                'verbose_name_plural': 'boxes',
                'ordering': ['nombre'],
                'unique_together': {('area', 'nombre')},
            },
        ),
    ]
