# Generated by Django 6.0.7 on 2026-08-02 14:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0012_alter_valorcampo_options'),
        ('instituciones', '0007_box_ocupado_desde_box_ocupado_por'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej.: «101-A», «UTI 3»', max_length=80)),
                ('estado', models.CharField(choices=[('libre', 'Libre'), ('ocupada', 'Ocupada'), ('higiene', 'En higiene'), ('bloqueada', 'Fuera de servicio')], default='libre', max_length=20)),
                ('desde', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camas', to='instituciones.area')),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camas', to='casos.caso')),
                ('subarea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='camas', to='instituciones.subarea', verbose_name='sector')),
            ],
            options={
                'verbose_name': 'cama',
                'verbose_name_plural': 'camas',
                'ordering': ['subarea__nombre', 'nombre'],
                'unique_together': {('area', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='EstadiaCama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desde', models.DateTimeField()),
                ('hasta', models.DateTimeField(blank=True, null=True)),
                ('motivo_egreso', models.CharField(blank=True, choices=[('alta', 'Alta'), ('pase', 'Pase a otro sector'), ('derivacion', 'Derivación a otra institución'), ('fallecimiento', 'Fallecimiento')], max_length=20)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estadias_asignadas', to=settings.AUTH_USER_MODEL)),
                ('cama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadias', to='instituciones.cama')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estadias', to='casos.caso')),
            ],
            options={
                'verbose_name': 'estadía en cama',
                'verbose_name_plural': 'estadías en cama',
                'ordering': ['-desde', '-id'],
            },
        ),
    ]
