# Generated by Django 6.0.7 on 2026-08-03 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0008_cama_estadiacama'),
    ]

    operations = [
        migrations.AddField(
            model_name='institucion',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='institucion',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
