# Generated by Django 5.2.15 on 2026-10-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institucion',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('en_alta', 'En configuración'), ('inactiva', 'Inactiva')], default='activa', max_length=20),
        ),
    ]
