# Generated by Django 6.0.7 on 2026-08-14 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        ('registros', '0004_alter_historiaclinica_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccesoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('detalle', 'Consulta de un registro'), ('listado', 'Consulta de un listado'), ('exportacion', 'Exportación a archivo')], max_length=20)),
                ('recurso', models.CharField(max_length=60)),
                ('objeto_id', models.CharField(blank=True, max_length=40)),
                ('detalle', models.CharField(blank=True, max_length=300)),
                ('resultados', models.PositiveIntegerField(default=0)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('momento', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ciudadano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accesos', to='registros.ciudadano')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accesos_clinicos', to='instituciones.institucion')),
                ('usuario', models.ForeignKey(help_text='No se borra con el usuario: el registro tiene que sobrevivirlo.', on_delete=django.db.models.deletion.PROTECT, related_name='accesos_clinicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'acceso a datos clínicos',
                'verbose_name_plural': 'accesos a datos clínicos',
                'ordering': ['-momento', '-id'],
                'indexes': [models.Index(fields=['ciudadano', '-momento'], name='auditoria_a_ciudada_3e3178_idx'), models.Index(fields=['usuario', '-momento'], name='auditoria_a_usuario_459e3a_idx')],
            },
        ),
    ]
