# Generated by Django 6.1 on 2026-08-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Latido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=60, unique=True)),
                ('momento', models.DateTimeField(auto_now=True)),
                ('detalle', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'latido de servicio',
                'verbose_name_plural': 'latidos de servicio',
                'ordering': ['servicio'],
            },
        ),
    ]
