# Generated by Django 5.2.15 on 2026-09-16 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_latido'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accesoclinico',
            name='tipo',
            field=models.CharField(choices=[('detalle', 'Consulta de un registro'), ('listado', 'Consulta de un listado'), ('exportacion', 'Exportación a archivo'), ('financiador', 'Consulta de un financiador')], max_length=20),
        ),
    ]
