# Generated by Django 5.2.15 on 2026-09-24 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0003_alter_accesoclinico_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesoclinico',
            name='motivo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='accesoclinico',
            name='variante',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
