# Generated by Django 5.2.15 on 2026-09-29 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0004_accesoclinico_motivo_accesoclinico_variante'),
        ('simulacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesoclinico',
            name='simulacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accesos_clinicos', to='simulacion.sesionsimulacion'),
        ),
    ]
