# Generated by Django 5.2.15 on 2026-10-08 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0005_accesoclinico_simulacion'),
        ('instituciones', '0010_institucion_estado_en_configuracion'),
        ('portal', '0002_tabla_cache'),
        ('registros', '0011_consentimientodatos_consentimiento_referido_and_more'),
        ('simulacion', '0002_cuenta_estatal_global'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accesoclinico',
            name='cuenta_paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accesos_clinicos', to='portal.cuentapaciente'),
        ),
        migrations.AlterField(
            model_name='accesoclinico',
            name='tipo',
            field=models.CharField(choices=[('detalle', 'Consulta de un registro'), ('listado', 'Consulta de un listado'), ('exportacion', 'Exportación a archivo'), ('financiador', 'Consulta de un financiador'), ('paciente', 'Consulta del propio paciente')], max_length=20),
        ),
        migrations.AlterField(
            model_name='accesoclinico',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='No se borra con el usuario: el registro tiene que sobrevivirlo.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accesos_clinicos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='accesoclinico',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cuenta_paciente__isnull', True), ('usuario__isnull', False)), models.Q(('cuenta_paciente__isnull', False), ('tipo', 'paciente'), ('usuario__isnull', True)), _connector='OR'), name='acceso_con_un_solo_autor'),
        ),
    ]
