# Generated by Django 5.2.15 on 2026-09-29 17:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('financiadores', '0007_responsabilidad_autorizaciones'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionSimulacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ambito', models.CharField(choices=[('plataforma', 'Plataforma'), ('institucion', 'Institución'), ('financiador', 'Financiador')], max_length=20)),
                ('rol', models.CharField(max_length=20)),
                ('iniciada', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('vence', models.DateTimeField()),
                ('finalizada', models.DateTimeField(blank=True, null=True)),
                ('fin', models.CharField(blank=True, choices=[('salida', 'Volvió a Sistema'), ('reemplazo', 'Eligió otro perfil o ámbito'), ('cierre', 'Cerró la sesión'), ('vencimiento', 'Venció'), ('invalida', 'La cuenta o el ámbito dejaron de ser válidos')], max_length=20)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('financiador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='financiadores.financiador')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='instituciones.institucion')),
                ('superusuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sesión de simulación',
                'verbose_name_plural': 'sesiones de simulación',
                'ordering': ['-iniciada'],
            },
        ),
        migrations.CreateModel(
            name='OperacionSimulada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo', models.CharField(max_length=10)),
                ('ruta', models.CharField(max_length=300)),
                ('estado', models.PositiveSmallIntegerField()),
                ('momento', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='simulacion.sesionsimulacion')),
            ],
            options={
                'verbose_name': 'operación simulada',
                'verbose_name_plural': 'operaciones simuladas',
                'ordering': ['-momento', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CuentaReferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito', models.CharField(choices=[('plataforma', 'Plataforma'), ('institucion', 'Institución'), ('financiador', 'Financiador')], max_length=20)),
                ('rol', models.CharField(max_length=20)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('financiador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='financiadores.financiador')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='instituciones.institucion')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_referencia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cuenta de referencia',
                'verbose_name_plural': 'cuentas de referencia',
                'ordering': ['ambito', 'rol', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('ambito', 'financiador'), ('financiador__isnull', False), ('institucion__isnull', True)), models.Q(('ambito__in', ['plataforma', 'institucion']), ('financiador__isnull', True), ('institucion__isnull', False)), _connector='OR'), name='simulacion_cuenta_ambito_valido'), models.UniqueConstraint(condition=models.Q(('ambito', 'plataforma')), fields=('rol',), name='simulacion_cuenta_plataforma_unica'), models.UniqueConstraint(condition=models.Q(('ambito', 'institucion')), fields=('rol', 'institucion'), name='simulacion_cuenta_institucion_unica'), models.UniqueConstraint(condition=models.Q(('ambito', 'financiador')), fields=('rol', 'financiador'), name='simulacion_cuenta_financiador_unica')],
            },
        ),
        migrations.AddIndex(
            model_name='sesionsimulacion',
            index=models.Index(fields=['superusuario', 'finalizada'], name='simulacion__superus_2be174_idx'),
        ),
    ]
