# Generated by Django 6.1.1 on 2026-09-08 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0013_itemfila_turno_a_ticket'),
        ('flujos', '0007_alter_nodo_tipo'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        ('registros', '0009_archivoclinico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HechoAtencionCosteable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento_origen_id', models.BigIntegerField(unique=True)),
                ('caso_origen_id', models.BigIntegerField()),
                ('ciudadano_origen_id', models.BigIntegerField(blank=True, null=True)),
                ('nodo_origen_id', models.BigIntegerField()),
                ('area_origen_id', models.BigIntegerField(blank=True, null=True)),
                ('ocurrida_en', models.DateTimeField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos_costo', to='instituciones.area')),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos_costo', to=settings.AUTH_USER_MODEL)),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos_costo', to='casos.eventocaso')),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos_costo', to='casos.caso')),
                ('ciudadano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos_costo', to='registros.ciudadano')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hechos_atencion_costeables', to='instituciones.institucion')),
                ('nodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hechos_costo', to='flujos.nodo')),
            ],
            options={
                'ordering': ['ocurrida_en', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Prestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestaciones_costo', to='instituciones.institucion')),
                ('nodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestaciones_costo', to='flujos.nodo')),
            ],
            options={
                'ordering': ['institucion_id', 'codigo'],
                'unique_together': {('institucion', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='DefinicionComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=160)),
                ('fuente', models.CharField(choices=[('atencion_directa', 'Atención directa')], default='atencion_directa', max_length=40)),
                ('activo', models.BooleanField(default=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes', to='finanzas.prestacion')),
            ],
            options={
                'ordering': ['prestacion_id', 'orden', 'id'],
                'unique_together': {('prestacion', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ValorComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vigente_desde', models.DateTimeField()),
                ('vigente_hasta', models.DateTimeField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, max_length=255)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('motivo_correccion', models.CharField(blank=True, max_length=255)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valores', to='finanzas.definicioncomponente')),
                ('reemplaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reemplazado_por', to='finanzas.valorcomponente')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores_costo_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['componente_id', 'vigente_desde', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ImputacionCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones', to='finanzas.definicioncomponente')),
                ('hecho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones', to='finanzas.hechoatencioncosteable')),
                ('valor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='imputaciones', to='finanzas.valorcomponente')),
            ],
        ),
        migrations.CreateModel(
            name='PendienteCosteo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.CharField(choices=[('sin_prestacion', 'Sin prestación configurada'), ('sin_valor', 'Sin valor vigente'), ('error_recuperable', 'Error recuperable')], max_length=40)),
                ('resuelto', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('componente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pendientes', to='finanzas.definicioncomponente')),
                ('hecho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pendientes', to='finanzas.hechoatencioncosteable')),
            ],
            options={
                'unique_together': {('hecho', 'componente', 'motivo')},
            },
        ),
        migrations.AddConstraint(
            model_name='valorcomponente',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gte', 0)), name='valor_componente_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='valorcomponente',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gt', models.F('vigente_desde')), _connector='OR'), name='vigencia_componente_valida'),
        ),
        migrations.AddConstraint(
            model_name='imputacioncosto',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gte', 0)), name='imputacion_costo_no_negativa'),
        ),
        migrations.AlterUniqueTogether(
            name='imputacioncosto',
            unique_together={('hecho', 'componente')},
        ),
    ]
