# Generated by Django 6.1.1 on 2026-09-08 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendientecosteo',
            name='motivo',
            field=models.CharField(choices=[('sin_prestacion', 'Sin prestación configurada'), ('sin_componentes', 'Sin componentes configurados'), ('sin_valor', 'Sin valor vigente'), ('error_recuperable', 'Error recuperable')], max_length=40),
        ),
        migrations.CreateModel(
            name='ComponenteEsperadoHecho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('componente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='hechos_esperados', to='finanzas.definicioncomponente')),
                ('hecho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='componentes_esperados', to='finanzas.hechoatencioncosteable')),
            ],
            options={
                'unique_together': {('hecho', 'componente')},
            },
        ),
    ]
