# Generated by Django 6.1.1 on 2026-09-08 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_membresia_rol'),
        ('finanzas', '0002_alter_pendientecosteo_motivo_componenteesperadohecho'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcesionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('ver_costos', 'Ver costos'), ('configurar_componentes', 'Configurar componentes'), ('corregir_costos', 'Corregir costos')], max_length=40)),
                ('todas_las_areas', models.BooleanField(default=False)),
                ('permite_sensibles', models.BooleanField(default=False)),
                ('areas', models.ManyToManyField(blank=True, related_name='concesiones_financieras', to='instituciones.area')),
                ('membresia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concesiones_financieras', to='accounts.membresia')),
            ],
            options={
                'ordering': ['membresia_id', 'accion', 'id'],
                'unique_together': {('membresia', 'accion')},
            },
        ),
    ]
