# Generated by Django 6.1.1 on 2026-09-08 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0003_concesionfinanciera'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motivo', models.CharField(max_length=255)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('imputacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='finanzas.imputacioncosto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_costo_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['registrado', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('importe', 0), _negated=True), name='ajuste_costo_no_cero')],
            },
        ),
    ]
