# Generated by Django 6.1.1 on 2026-09-08 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0004_ajustecosto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pendientecosteo',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='pendientecosteo',
            constraint=models.UniqueConstraint(condition=models.Q(('componente__isnull', True)), fields=('hecho', 'motivo'), name='pendiente_sin_componente_unico'),
        ),
        migrations.AddConstraint(
            model_name='pendientecosteo',
            constraint=models.UniqueConstraint(condition=models.Q(('componente__isnull', False)), fields=('hecho', 'componente', 'motivo'), name='pendiente_con_componente_unico'),
        ),
    ]
