# Generated by Django 6.1.1 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0005_alter_pendientecosteo_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="hechoatencioncosteable",
            name="componentes_congelados",
            field=models.BooleanField(default=False),
        ),
    ]
