# Generated by Django 6.1.1 on 2026-09-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0006_hechoatencioncosteable_componentes_congelados"),
    ]

    operations = [
        migrations.AlterField(
            model_name="valorcomponente",
            name="reemplaza",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reemplazado_por",
                to="finanzas.valorcomponente",
            ),
        ),
    ]
