# Generated by Django 6.1.1 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0007_alter_valorcomponente_reemplaza"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendientecosteo",
            name="motivo",
            field=models.CharField(
                choices=[
                    ("sin_prestacion", "Sin prestación configurada"),
                    ("sin_componentes", "Sin componentes configurados"),
                    ("sin_valor", "Sin valor vigente"),
                    ("error_recuperable", "Error recuperable"),
                    ("snapshot_incompleto", "No se pudo congelar el catálogo aplicable"),
                ],
                max_length=40,
            ),
        ),
    ]
