# Generated by Django 6.1.1 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0009_correccionsnapshotcosteo"),
    ]

    operations = [
        migrations.AddField(
            model_name="hechoatencioncosteable",
            name="ultimo_costeo_en",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
