# Generated by Django 6.1.1 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0010_hechoatencioncosteable_ultimo_costeo_en"),
    ]

    operations = [
        migrations.AddField(
            model_name="componenteesperadohecho",
            name="sensible",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="definicioncomponente",
            name="sensible",
            field=models.BooleanField(default=False),
        ),
    ]
