# Generated by Django 6.1.1 on 2026-09-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0011_sensibilidad_componentes"),
    ]

    operations = [
        migrations.AddField(
            model_name="componenteesperadohecho",
            name="base_calculo",
            field=models.CharField(
                choices=[("por_atencion", "Por atención")],
                default="por_atencion",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="componenteesperadohecho",
            name="unidad",
            field=models.CharField(
                choices=[("atencion", "Atención")],
                default="atencion",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="definicioncomponente",
            name="base_calculo",
            field=models.CharField(
                choices=[("por_atencion", "Por atención")],
                default="por_atencion",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="definicioncomponente",
            name="unidad",
            field=models.CharField(
                choices=[("atencion", "Atención")],
                default="atencion",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="imputacioncosto",
            name="base_calculo",
            field=models.CharField(
                choices=[("por_atencion", "Por atención")],
                default="por_atencion",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="imputacioncosto",
            name="moneda",
            field=models.CharField(
                choices=[("ARS", "Peso argentino")],
                default="ARS",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="imputacioncosto",
            name="unidad",
            field=models.CharField(
                choices=[("atencion", "Atención")],
                default="atencion",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="valorcomponente",
            name="moneda",
            field=models.CharField(
                choices=[("ARS", "Peso argentino")],
                default="ARS",
                max_length=3,
            ),
        ),
    ]
