# Generated by Django 6.1.1 on 2026-09-08 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0012_unidad_base_y_moneda_del_costo_directo'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('sensible', models.BooleanField(default=False)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conceptos_gasto', to='instituciones.institucion')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conceptos_gasto_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['institucion_id', 'codigo', 'id'],
                'unique_together': {('institucion', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ExpectativaGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('sensible', models.BooleanField(default=False, editable=False)),
                ('motivo_correccion', models.CharField(blank=True, max_length=255)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expectativas_gasto', to='instituciones.area')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expectativas', to='finanzas.conceptogasto')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expectativas_gasto', to='instituciones.institucion')),
                ('reemplaza', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reemplazada_por', to='finanzas.expectativagasto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expectativas_gasto_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['institucion_id', 'concepto_id', 'area_id', 'vigente_desde', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gt', models.F('vigente_desde')), _connector='OR'), name='vigencia_expectativa_gasto_valida')],
            },
        ),
    ]
