# Generated by Django 6.1.1 on 2026-09-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0013_conceptogasto_expectativagasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesionfinanciera',
            name='accion',
            field=models.CharField(choices=[('ver_costos', 'Ver costos'), ('configurar_componentes', 'Configurar componentes'), ('corregir_costos', 'Corregir costos'), ('ver_gastos', 'Ver gastos'), ('registrar_gastos', 'Registrar gastos'), ('aprobar_gastos', 'Aprobar gastos'), ('corregir_gastos', 'Corregir gastos'), ('configurar_gastos_esperados', 'Configurar gastos esperados')], max_length=40),
        ),
    ]
