# Generated by Django 6.1.1 on 2026-09-08 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0014_alter_concesionfinanciera_accion'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto_codigo', models.CharField(editable=False, max_length=60)),
                ('concepto_nombre', models.CharField(editable=False, max_length=160)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('moneda', models.CharField(default='ARS', editable=False, max_length=3)),
                ('periodo_economico', models.DateField()),
                ('origen', models.CharField(choices=[('central', 'Administración central'), ('area', 'Área')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente_aprobacion', max_length=30)),
                ('sensible', models.BooleanField(default=False, editable=False)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('rechazado_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=255)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='instituciones.area')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='finanzas.conceptogasto')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gastos', to='instituciones.institucion')),
                ('rechazado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_rechazados', to=settings.AUTH_USER_MODEL)),
                ('reemplaza', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reemplazado_por', to='finanzas.gasto')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['periodo_economico', 'institucion_id', 'area_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AjusteGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motivo', models.CharField(max_length=255)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_gasto_registrados', to=settings.AUTH_USER_MODEL)),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes', to='finanzas.gasto')),
            ],
            options={
                'ordering': ['registrado', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='gasto',
            constraint=models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='gasto_importe_positivo'),
        ),
        migrations.AddConstraint(
            model_name='ajustegasto',
            constraint=models.CheckConstraint(condition=models.Q(('importe', 0), _negated=True), name='ajuste_gasto_no_cero'),
        ),
    ]
