# Generated by Django 6.1.1 on 2026-09-08 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finanzas", "0015_gasto_ajustegasto_gasto_gasto_importe_positivo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IndicacionCargaGasto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("periodo_economico", models.DateField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("falta_cargar", "Falta cargar"),
                            ("carga_completa", "Carga completa"),
                            ("no_corresponde", "No corresponde"),
                        ],
                        max_length=30,
                    ),
                ),
                ("registrado", models.DateTimeField(auto_now_add=True)),
                (
                    "expectativa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="indicaciones_carga",
                        to="finanzas.expectativagasto",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="indicaciones_carga_gasto_registradas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["periodo_economico", "registrado", "id"],
            },
        ),
    ]
