# Generated by Django 6.1.1 on 2026-09-08 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0016_indicacioncargagasto'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesionfinanciera',
            name='accion',
            field=models.CharField(choices=[('ver_costos', 'Ver costos'), ('configurar_componentes', 'Configurar componentes'), ('corregir_costos', 'Corregir costos'), ('ver_gastos', 'Ver gastos'), ('registrar_gastos', 'Registrar gastos'), ('aprobar_gastos', 'Aprobar gastos'), ('corregir_gastos', 'Corregir gastos'), ('configurar_gastos_esperados', 'Configurar gastos esperados'), ('auditar_finanzas', 'Auditar accesos financieros')], max_length=40),
        ),
        migrations.CreateModel(
            name='AccesoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensible', models.BooleanField(default=False)),
                ('recurso', models.CharField(max_length=60)),
                ('accion', models.CharField(max_length=30)),
                ('objeto_id', models.PositiveBigIntegerField(null=True)),
                ('periodo_economico', models.DateField(null=True)),
                ('resultados', models.PositiveIntegerField(default=0)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instituciones.area')),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instituciones.institucion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registrado', '-id'],
            },
        ),
    ]
