# Generated by Django 6.1.1 on 2026-09-08 22:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0017_acceso_financiero'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='concesionfinanciera',
            name='accion',
            field=models.CharField(choices=[('ver_costos', 'Ver costos'), ('configurar_componentes', 'Configurar componentes'), ('corregir_costos', 'Corregir costos'), ('ver_gastos', 'Ver gastos'), ('registrar_gastos', 'Registrar gastos'), ('aprobar_gastos', 'Aprobar gastos'), ('corregir_gastos', 'Corregir gastos'), ('configurar_gastos_esperados', 'Configurar gastos esperados'), ('auditar_finanzas', 'Auditar accesos financieros'), ('configurar_repartos', 'Configurar repartos')], max_length=40),
        ),
        migrations.CreateModel(
            name='CoberturaActividadCosteable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('motivo_correccion', models.CharField(blank=True, max_length=255)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituciones.area')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituciones.institucion')),
                ('reemplaza', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reemplazada_por', to='finanzas.coberturaactividadcosteable')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coberturas_actividad_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['institucion_id', 'area_id', 'vigente_desde', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ReglaRepartoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vigente_desde', models.DateField()),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('sensible', models.BooleanField(default=False, editable=False)),
                ('motivo_correccion', models.CharField(blank=True, max_length=255)),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituciones.area')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.conceptogasto')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituciones.institucion')),
                ('reemplaza', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reemplazada_por', to='finanzas.reglarepartoactividad')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reglas_reparto_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['institucion_id', 'area_id', 'concepto_id', 'vigente_desde', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RepartoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('huella_insumos', models.CharField(max_length=64)),
                ('importe_fuente_centavos', models.BigIntegerField()),
                ('importe_ajustes_centavos', models.BigIntegerField()),
                ('saldo_centavos', models.BigIntegerField()),
                ('saldo_no_atribuido_centavos', models.BigIntegerField(default=0)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('distribuido', 'Distribuido'), ('sin_actividad', 'Sin actividad acreditada')], max_length=20)),
                ('motivo', models.CharField(blank=True, choices=[('sin_regla', 'Sin regla aplicable'), ('sin_cobertura', 'Sin cobertura acreditada'), ('fuente_no_elegible', 'Fuente no elegible')], max_length=30)),
                ('calculado', models.DateTimeField(auto_now_add=True)),
                ('cobertura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.coberturaactividadcosteable')),
                ('gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='repartos', to='finanzas.gasto')),
                ('reemplaza', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reemplazado_por', to='finanzas.repartogasto')),
                ('regla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.reglarepartoactividad')),
            ],
            options={
                'ordering': ['gasto_id', 'version'],
            },
        ),
        migrations.CreateModel(
            name='AtribucionReparto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_centavos', models.BigIntegerField()),
                ('hecho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuciones_reparto', to='finanzas.hechoatencioncosteable')),
                ('reparto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='atribuciones', to='finanzas.repartogasto')),
            ],
            options={
                'ordering': ['reparto_id', 'hecho_id'],
            },
        ),
        migrations.AddConstraint(
            model_name='coberturaactividadcosteable',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gt', models.F('vigente_desde')), _connector='OR'), name='vigencia_cobertura_actividad_valida'),
        ),
        migrations.AddConstraint(
            model_name='reglarepartoactividad',
            constraint=models.CheckConstraint(condition=models.Q(('vigente_hasta__isnull', True), ('vigente_hasta__gt', models.F('vigente_desde')), _connector='OR'), name='vigencia_regla_reparto_valida'),
        ),
        migrations.AddConstraint(
            model_name='repartogasto',
            constraint=models.UniqueConstraint(fields=('gasto', 'version'), name='version_reparto_gasto_unica'),
        ),
        migrations.AddConstraint(
            model_name='repartogasto',
            constraint=models.UniqueConstraint(fields=('gasto', 'huella_insumos'), name='insumos_reparto_gasto_unicos'),
        ),
        migrations.AddConstraint(
            model_name='atribucionreparto',
            constraint=models.UniqueConstraint(fields=('reparto', 'hecho'), name='atribucion_reparto_hecho_unica'),
        ),
    ]
