# Generated by Django 6.1.1 on 2026-09-14 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0023_cobros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustecosto',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajustecosto',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajustecosto',
            name='estado',
            field=models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='aprobado', max_length=30),
        ),
        migrations.AddField(
            model_name='ajustecosto',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ajustecosto',
            name='rechazado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajustecosto',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_rechazados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajustegasto',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajustegasto',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajustegasto',
            name='estado',
            field=models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='aprobado', max_length=30),
        ),
        migrations.AddField(
            model_name='ajustegasto',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ajustegasto',
            name='rechazado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajustegasto',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_rechazados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajusteobligacion',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajusteobligacion',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ajusteobligacion',
            name='estado',
            field=models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='aprobado', max_length=30),
        ),
        migrations.AddField(
            model_name='ajusteobligacion',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='ajusteobligacion',
            name='rechazado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ajusteobligacion',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_rechazados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientodinero',
            name='aprobado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientodinero',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientodinero',
            name='estado',
            field=models.CharField(choices=[('pendiente_aprobacion', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='aprobado', max_length=30),
        ),
        migrations.AddField(
            model_name='movimientodinero',
            name='motivo_rechazo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='movimientodinero',
            name='rechazado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientodinero',
            name='rechazado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(app_label)s_%(class)s_rechazados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='concesionfinanciera',
            name='accion',
            field=models.CharField(choices=[('ver_costos', 'Ver costos'), ('configurar_componentes', 'Configurar componentes'), ('corregir_costos', 'Corregir costos'), ('aprobar_costos', 'Aprobar ajustes de costos'), ('ver_gastos', 'Ver gastos'), ('registrar_gastos', 'Registrar gastos'), ('aprobar_gastos', 'Aprobar gastos'), ('corregir_gastos', 'Corregir gastos'), ('configurar_gastos_esperados', 'Configurar gastos esperados'), ('auditar_finanzas', 'Auditar accesos financieros'), ('configurar_repartos', 'Configurar repartos'), ('ver_dinero', 'Ver pagos y cobros'), ('registrar_dinero', 'Registrar pagos y cobros'), ('aprobar_dinero', 'Aprobar pagos, cobros y correcciones'), ('corregir_dinero', 'Reducir obligaciones y reintegrar dinero'), ('configurar_cobros', 'Configurar cobros')], max_length=40),
        ),
    ]
