# Generated by Django 5.2.15 on 2026-09-16 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0024_aprobaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='hechoatencioncosteable',
            name='cobertura_contexto',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='concesionfinanciera',
            name='accion',
            field=models.CharField(choices=[('ver_costos', 'Ver costos'), ('configurar_componentes', 'Configurar componentes'), ('corregir_costos', 'Corregir costos'), ('aprobar_costos', 'Aprobar ajustes de costos'), ('ver_gastos', 'Ver gastos'), ('registrar_gastos', 'Registrar gastos'), ('aprobar_gastos', 'Aprobar gastos'), ('corregir_gastos', 'Corregir gastos'), ('configurar_gastos_esperados', 'Configurar gastos esperados'), ('auditar_finanzas', 'Auditar accesos financieros'), ('configurar_repartos', 'Configurar repartos'), ('ver_dinero', 'Ver pagos y cobros'), ('registrar_dinero', 'Registrar pagos y cobros'), ('aprobar_dinero', 'Aprobar pagos, cobros y correcciones'), ('corregir_dinero', 'Reducir obligaciones y reintegrar dinero'), ('configurar_cobros', 'Configurar cobros'), ('registrar_aceptacion', 'Registrar aceptación de copago'), ('resolver_cobertura', 'Resolver saldos de cobertura')], max_length=40),
        ),
    ]
