# Generated by Django 5.2.15 on 2026-09-18 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0025_hechoatencioncosteable_cobertura_contexto_and_more'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='coberturaactividadcosteable',
            name='habilitada',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='coberturaactividadcosteable',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instituciones.area'),
        ),
        migrations.AlterField(
            model_name='reglarepartoactividad',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='instituciones.area'),
        ),
    ]
