# Generated by Django 6.0.6 on 2026-06-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin de institución'), ('configurador', 'Configurador'), ('administrativo', 'Administrativo'), ('medico', 'Médico / profesional')], max_length=20),
        ),
    ]
