# Generated by Django 6.0.6 on 2026-06-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_membresia_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin de institución'), ('configurador', 'Configurador'), ('jefe_area', 'Jefe / Supervisor de área'), ('administrativo', 'Administrativo'), ('enfermeria', 'Enfermería'), ('medico', 'Médico / profesional')], max_length=20),
        ),
    ]
