# Generated by Django 6.0.7 on 2026-08-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_membresia_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legajoprofesional',
            options={'ordering': ['id'], 'verbose_name': 'legajo profesional', 'verbose_name_plural': 'legajos profesionales'},
        ),
        migrations.AlterModelOptions(
            name='membresia',
            options={'ordering': ['institucion_id', 'rol', 'id'], 'verbose_name': 'membresía', 'verbose_name_plural': 'membresías'},
        ),
    ]
