# Generated by Django 6.0.6 on 2026-08-19 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_legajoprofesional_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membresia',
            name='rol',
            field=models.CharField(choices=[('plataforma', 'Autoridad estatal / plataforma'), ('auditor', 'Auditor estatal'), ('reportes', 'Reportes / solo lectura'), ('admin', 'Admin de institución'), ('configurador', 'Configurador'), ('jefe_area', 'Jefe / Supervisor de área'), ('administrativo', 'Administrativo'), ('enfermeria', 'Enfermería'), ('medico', 'Médico / profesional')], max_length=20),
        ),
    ]
