# Generated by Django 5.2.15 on 2026-09-16 00:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0013_itemfila_turno_a_ticket'),
        ('finanzas', '0025_hechoatencioncosteable_cobertura_contexto_and_more'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        ('registros', '0009_archivoclinico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('obra_social', 'Obra social'), ('mutual', 'Mutual'), ('otro', 'Otro financiador')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PrestacionComun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=160)),
                ('categoria', models.CharField(max_length=80)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionHospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=False)),
                ('dias_reserva_antigua', models.PositiveIntegerField(default=7)),
                ('institucion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='instituciones.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('propuesto', 'Propuesto'), ('activo', 'Activo'), ('rechazado', 'Rechazado')], default='propuesto', max_length=12)),
                ('propuesto_por', models.CharField(choices=[('hospital', 'Hospital'), ('financiador', 'Financiador'), ('plataforma', 'Plataforma')], max_length=12)),
                ('porcentaje_default', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('aceptado_en', models.DateTimeField(null=True)),
                ('aceptado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenios_aceptados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convenios_creados', to=settings.AUTH_USER_MODEL)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituciones.institucion')),
                ('financiador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.financiador')),
            ],
        ),
        migrations.CreateModel(
            name='EventoCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=60)),
                ('objeto', models.CharField(max_length=80)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='instituciones.institucion')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('financiador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='financiadores.financiador')),
            ],
        ),
        migrations.CreateModel(
            name='Afiliado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=80)),
                ('documento', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=160)),
                ('desde', models.DateField()),
                ('financiador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.financiador')),
            ],
            options={
                'ordering': ['nombre', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Importacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=10)),
                ('clave', models.UUIDField()),
                ('huella', models.CharField(max_length=64)),
                ('filas', models.JSONField(default=list)),
                ('estado', models.CharField(default='preview', max_length=20)),
                ('resumen', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('financiador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.financiador')),
            ],
        ),
        migrations.CreateModel(
            name='MembresiaFinanciador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('auditor', 'Auditor')], max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('financiador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.financiador')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=60)),
                ('nombre', models.CharField(max_length=160)),
                ('activo', models.BooleanField(default=True)),
                ('financiador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.financiador')),
            ],
            options={
                'ordering': ['codigo', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HistorialAfiliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=80)),
                ('desde', models.DateField()),
                ('registrado', models.DateTimeField(auto_now_add=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='financiadores.afiliado')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financiadores.plan')),
            ],
        ),
        migrations.AddField(
            model_name='afiliado',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financiadores.plan'),
        ),
        migrations.CreateModel(
            name='AfiliacionCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('verificada', 'Verificada'), ('pendiente', 'Pendiente'), ('particular', 'Particular')], max_length=12)),
                ('declaracion', models.CharField(blank=True, max_length=160)),
                ('motivo', models.CharField(max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afiliaciones_financieras', to='casos.caso')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('afiliado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='financiadores.afiliado')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='financiadores.plan')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ConsumoExterno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.IntegerField()),
                ('referencia', models.CharField(blank=True, max_length=120)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.afiliado')),
                ('corrige', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='correccion', to='financiadores.consumoexterno')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('financiador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.financiador')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.prestacioncomun')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReglaCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cupo', models.PositiveIntegerField(blank=True, null=True)),
                ('periodo', models.CharField(choices=[('mes', 'Mes calendario'), ('anio', 'Año calendario')], default='anio', max_length=4)),
                ('vigente_desde', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('financiador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.financiador')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financiadores.plan')),
                ('prestacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financiadores.prestacioncomun')),
            ],
            options={
                'ordering': ['-vigente_desde', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReservaCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cantidad', models.PositiveIntegerField()),
                ('cubiertas', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('reservada', 'Reservada'), ('realizada', 'Realizada'), ('liberada', 'Liberada')], default='reservada', max_length=12)),
                ('evaluacion', models.JSONField()),
                ('aceptacion', models.JSONField(default=dict)),
                ('discrepancia', models.BooleanField(default=False)),
                ('clave', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('solicitud', models.JSONField(default=dict)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(null=True)),
                ('motivo', models.CharField(blank=True, max_length=255)),
                ('afiliacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.afiliacioncaso')),
                ('afiliado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='financiadores.afiliado')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='casos.caso')),
                ('cerrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cierres_cobertura', to=settings.AUTH_USER_MODEL)),
                ('comun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.prestacioncomun')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservas_cobertura', to=settings.AUTH_USER_MODEL)),
                ('hecho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.hechoatencioncosteable')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.prestacion')),
            ],
        ),
        migrations.CreateModel(
            name='DistribucionCobro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe_financiador', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('importe_paciente', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de resolución administrativa'), ('resuelta', 'Resuelta'), ('arancel_pendiente', 'Arancel pendiente'), ('evaluacion_pendiente', 'Pendiente de evaluación'), ('sin_cobro', 'Sin cobro')], default='pendiente', max_length=25)),
                ('obligacion_financiador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribucion_financiador', to='finanzas.obligacionfinanciera')),
                ('obligacion_paciente', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='distribucion_paciente', to='finanzas.obligacionfinanciera')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='distribucion', to='financiadores.reservacobertura')),
            ],
        ),
        migrations.CreateModel(
            name='ResolucionSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('rechazar', 'Rechazar asunción'), ('asumir', 'Asumir hospital'), ('paciente', 'Aceptación paciente'), ('financiador', 'Aceptación financiador')], max_length=12)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('motivo', models.CharField(max_length=255)),
                ('evidencia', models.TextField(blank=True)),
                ('clave', models.UUIDField(unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('distribucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resoluciones', to='financiadores.distribucioncobro')),
                ('obligacion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.obligacionfinanciera')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VinculoCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.afiliado')),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registros.ciudadano')),
                ('verificado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VinculoPrestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.prestacioncomun')),
                ('prestacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='finanzas.prestacion')),
            ],
        ),
        migrations.CreateModel(
            name='ArancelConvenio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('vigente_desde', models.DateField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.prestacion')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.convenio')),
            ],
            options={
                'ordering': ['-vigente_desde', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('importe__isnull', True), ('importe__gt', 0), _connector='OR'), name='fin_arancel_excepcion_positivo')],
            },
        ),
        migrations.AddConstraint(
            model_name='convenio',
            constraint=models.UniqueConstraint(fields=('financiador', 'institucion'), name='fin_convenio_unico'),
        ),
        migrations.AddConstraint(
            model_name='importacion',
            constraint=models.UniqueConstraint(fields=('financiador', 'clave'), name='fin_importacion_clave'),
        ),
        migrations.AddConstraint(
            model_name='membresiafinanciador',
            constraint=models.UniqueConstraint(fields=('financiador', 'usuario'), name='fin_membresia_unica'),
        ),
        migrations.AddConstraint(
            model_name='plan',
            constraint=models.UniqueConstraint(fields=('financiador', 'codigo'), name='fin_plan_codigo'),
        ),
        migrations.AddConstraint(
            model_name='afiliado',
            constraint=models.UniqueConstraint(fields=('financiador', 'documento'), name='fin_afiliado_documento'),
        ),
        migrations.AddIndex(
            model_name='consumoexterno',
            index=models.Index(fields=['afiliado', 'prestacion', 'fecha'], name='financiador_afiliad_1fed67_idx'),
        ),
        migrations.AddConstraint(
            model_name='consumoexterno',
            constraint=models.UniqueConstraint(condition=models.Q(('referencia', ''), _negated=True), fields=('financiador', 'referencia'), name='fin_consumo_referencia'),
        ),
        migrations.AddConstraint(
            model_name='reglacobertura',
            constraint=models.CheckConstraint(condition=models.Q(('porcentaje__gte', 0), ('porcentaje__lte', 100)), name='fin_porcentaje_valido'),
        ),
        migrations.AddIndex(
            model_name='reservacobertura',
            index=models.Index(fields=['afiliado', 'comun', 'fecha', 'estado'], name='financiador_afiliad_fb0c92_idx'),
        ),
        migrations.AddConstraint(
            model_name='reservacobertura',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0), ('cubiertas__lte', models.F('cantidad'))), name='fin_reserva_cantidades'),
        ),
        migrations.AddConstraint(
            model_name='vinculociudadano',
            constraint=models.UniqueConstraint(fields=('afiliado', 'ciudadano'), name='fin_vinculo_ciudadano'),
        ),
    ]
