# Generated by Django 5.2.15 on 2026-09-16 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiadores', '0001_initial'),
        ('finanzas', '0025_hechoatencioncosteable_cobertura_contexto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliacioncaso',
            name='hecho_revision',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.hechoatencioncosteable'),
        ),
        migrations.AlterField(
            model_name='afiliacioncaso',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RevisionContexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contexto', models.JSONField()),
                ('motivo', models.CharField(max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('hecho', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='finanzas.hechoatencioncosteable')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
