# Generated by Django 5.2.15 on 2026-09-16 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiadores', '0002_afiliacioncaso_hecho_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialafiliacion',
            name='documento',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
