# Generated by Django 5.2.15 on 2026-09-16 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiadores', '0003_historialafiliacion_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='membresiafinanciador',
            name='creo_cuenta',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
