# Generated by Django 5.2.15 on 2026-09-16 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiadores', '0004_membresiafinanciador_creo_cuenta'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='convenio',
            name='fin_convenio_unico',
        ),
        migrations.AddField(
            model_name='afiliado',
            name='finalizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='finalizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='afiliaciones_finalizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='afiliado',
            name='motivo_finalizacion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='convenio',
            name='cerrado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convenio',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convenios_cerrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='convenio',
            name='motivo_cierre',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historialafiliacion',
            name='motivo',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='historialafiliacion',
            name='tipo',
            field=models.CharField(choices=[('actualizacion', 'Actualización'), ('finalizacion', 'Finalización'), ('reactivacion', 'Reactivación')], default='actualizacion', max_length=15),
        ),
        migrations.AlterField(
            model_name='convenio',
            name='estado',
            field=models.CharField(choices=[('propuesto', 'Propuesto'), ('activo', 'Activo'), ('rechazado', 'Rechazado'), ('finalizado', 'Finalizado')], default='propuesto', max_length=12),
        ),
        migrations.AddConstraint(
            model_name='convenio',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['propuesto', 'activo'])), fields=('financiador', 'institucion'), name='fin_convenio_abierto_unico'),
        ),
    ]
