# Generated by Django 5.2.15 on 2026-09-16 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0013_itemfila_turno_a_ticket'),
        ('financiadores', '0005_remove_convenio_fin_convenio_unico_and_more'),
        ('finanzas', '0025_hechoatencioncosteable_cobertura_contexto_and_more'),
        ('flujos', '0007_alter_nodo_tipo'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        ('registros', '0009_archivoclinico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='plazo_autorizacion_horas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='membresiafinanciador',
            name='resuelve_autorizaciones',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reglacobertura',
            name='requiere_autorizacion',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='SolicitudAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intento', models.UUIDField()),
                ('cantidad_solicitada', models.PositiveIntegerField()),
                ('cantidad_aprobada', models.PositiveIntegerField(default=0)),
                ('justificacion', models.CharField(max_length=1000)),
                ('urgente', models.BooleanField(default=False)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('observada', 'Observada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vencida', 'Vencida'), ('anulada', 'Anulada')], default='pendiente', max_length=12)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('plazo_respuesta', models.DateTimeField(blank=True, null=True)),
                ('vigencia_desde', models.DateField(blank=True, null=True)),
                ('vigencia_hasta', models.DateField(blank=True, null=True)),
                ('numero_externo', models.CharField(blank=True, max_length=120)),
                ('motivo_resolucion', models.CharField(blank=True, max_length=255)),
                ('evidencia', models.CharField(blank=True, max_length=1000)),
                ('resuelto_en', models.DateTimeField(null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('anterior', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reintentos', to='financiadores.solicitudautorizacion')),
                ('afiliacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.afiliacioncaso')),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.afiliado')),
                ('caso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones', to='casos.caso')),
                ('ciudadano', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='registros.ciudadano')),
                ('comun', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.prestacioncomun')),
                ('convenio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.convenio')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_solicitadas', to=settings.AUTH_USER_MODEL)),
                ('financiador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.financiador')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='instituciones.institucion')),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='flujos.nodo')),
                ('prestacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finanzas.prestacion')),
                ('resuelto_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='EventoAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.UUIDField(unique=True)),
                ('accion', models.CharField(max_length=20)),
                ('anterior', models.CharField(blank=True, max_length=12)),
                ('estado', models.CharField(max_length=12)),
                ('revision', models.PositiveIntegerField()),
                ('motivo', models.CharField(max_length=1000)),
                ('peticion', models.JSONField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial', to='financiadores.solicitudautorizacion')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='UsoAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('comprometido', 'Comprometido'), ('consumido', 'Consumido'), ('liberado', 'Liberado')], default='comprometido', max_length=12)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('hecho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.hechoatencioncosteable')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='uso_autorizacion', to='financiadores.reservacobertura')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usos', to='financiadores.solicitudautorizacion')),
            ],
        ),
        migrations.AddIndex(
            model_name='solicitudautorizacion',
            index=models.Index(fields=['estado', 'plazo_respuesta'], name='financiador_estado_93b159_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudautorizacion',
            index=models.Index(fields=['convenio', 'afiliado', 'comun', 'estado'], name='financiador_conveni_ea9333_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudautorizacion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_solicitada__gt', 0), ('cantidad_aprobada__lte', models.F('cantidad_solicitada'))), name='fin_autorizacion_cantidades'),
        ),
        migrations.AddConstraint(
            model_name='solicitudautorizacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'aprobada'), _negated=True), models.Q(('cantidad_aprobada__gt', 0), ('vigencia_desde__isnull', False), ('vigencia_hasta__isnull', False), ('vigencia_hasta__gte', models.F('vigencia_desde'))), _connector='OR'), name='fin_autorizacion_vigencia'),
        ),
        migrations.AddConstraint(
            model_name='solicitudautorizacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'observada', 'aprobada'])), fields=('caso', 'intento', 'prestacion'), name='fin_autorizacion_intento_activo'),
        ),
        migrations.AddConstraint(
            model_name='usoautorizacion',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='fin_uso_autorizacion_positivo'),
        ),
    ]
