# Generated by Django 5.2.15 on 2026-09-16 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0014_caso_espera_autorizacion'),
        ('financiadores', '0006_autorizaciones_previas'),
        ('finanzas', '0025_hechoatencioncosteable_cobertura_contexto_and_more'),
        ('flujos', '0008_versionflujo_tipo_circuito'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        ('registros', '0009_archivoclinico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resolucionsaldo',
            name='parte',
            field=models.CharField(choices=[('paciente', 'Saldo del paciente'), ('financiador', 'Responsabilidad pendiente de autorización')], default='paciente', max_length=12),
        ),
        migrations.AlterField(
            model_name='distribucioncobro',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de resolución administrativa'), ('resuelta', 'Resuelta'), ('arancel_pendiente', 'Arancel pendiente'), ('evaluacion_pendiente', 'Pendiente de evaluación'), ('autorizacion_pendiente', 'Responsabilidad pendiente de autorización'), ('sin_cobro', 'Sin cobro')], default='pendiente', max_length=25),
        ),
        migrations.AddIndex(
            model_name='solicitudautorizacion',
            index=models.Index(fields=['estado', 'vigencia_hasta'], name='financiador_estado_ba879d_idx'),
        ),
    ]
