# Generated by Django 5.2.15 on 2026-09-30 18:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0014_caso_espera_autorizacion'),
        ('financiadores', '0007_responsabilidad_autorizaciones'),
        ('finanzas', '0027_accesofinanciero_simulacion'),
        ('flujos', '0008_versionflujo_tipo_circuito'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        ('registros', '0011_consentimientodatos_consentimiento_referido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudautorizacion',
            name='origen',
            field=models.CharField(choices=[('institucion', 'Institución'), ('manual', 'Manual')], default='institucion', max_length=12),
        ),
        migrations.AlterField(
            model_name='solicitudautorizacion',
            name='afiliacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financiadores.afiliacioncaso'),
        ),
        migrations.AlterField(
            model_name='solicitudautorizacion',
            name='caso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='autorizaciones', to='casos.caso'),
        ),
        migrations.AlterField(
            model_name='solicitudautorizacion',
            name='intento',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudautorizacion',
            name='nodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='flujos.nodo'),
        ),
        migrations.AlterField(
            model_name='solicitudautorizacion',
            name='prestacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finanzas.prestacion'),
        ),
        migrations.AddConstraint(
            model_name='solicitudautorizacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('afiliacion__isnull', False), ('caso__isnull', False), ('intento__isnull', False), ('nodo__isnull', False), ('origen', 'institucion'), ('prestacion__isnull', False)), models.Q(('afiliacion__isnull', True), ('caso__isnull', True), ('intento__isnull', True), ('nodo__isnull', True), ('origen', 'manual'), ('prestacion__isnull', True)), _connector='OR'), name='fin_autorizacion_origen_coherente'),
        ),
        migrations.AddConstraint(
            model_name='solicitudautorizacion',
            constraint=models.UniqueConstraint(condition=models.Q(('estado__in', ['pendiente', 'observada']), ('origen', 'manual')), fields=('afiliado', 'convenio', 'comun'), name='fin_autorizacion_manual_abierta'),
        ),
    ]
