# Generated by Django 5.2.15 on 2026-09-30 18:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiadores', '0008_solicitudautorizacion_origen_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroFactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('recibida', 'Recibida'), ('emitida', 'Emitida por el financiador')], max_length=10)),
                ('contraparte_tipo', models.CharField(choices=[('institucion', 'Institución'), ('afiliado', 'Afiliado')], max_length=12)),
                ('contraparte_nombre', models.CharField(max_length=160)),
                ('contraparte_identificador', models.CharField(blank=True, max_length=80)),
                ('tipo', models.CharField(choices=[('factura', 'Factura'), ('nota_credito', 'Nota de crédito'), ('nota_debito', 'Nota de débito'), ('otro', 'Otro')], max_length=16)),
                ('letra', models.CharField(blank=True, choices=[('', 'Ninguna'), ('A', 'A'), ('B', 'B'), ('C', 'C'), ('M', 'M')], max_length=1)),
                ('numero', models.CharField(max_length=120)),
                ('fecha', models.DateField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=14)),
                ('periodo', models.CharField(blank=True, max_length=100)),
                ('concepto', models.CharField(blank=True, max_length=255)),
                ('observaciones', models.TextField(blank=True)),
                ('clave_duplicado', models.CharField(max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('adjunto_ruta', models.CharField(blank=True, max_length=255)),
                ('adjunto_nombre', models.CharField(blank=True, max_length=255)),
                ('adjunto_content_type', models.CharField(blank=True, max_length=80)),
                ('adjunto_tamano', models.PositiveIntegerField(blank=True, null=True)),
                ('adjunto_sha256', models.CharField(blank=True, max_length=64)),
                ('adjunto_fecha', models.DateTimeField(blank=True, null=True)),
                ('adjunto_subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='facturas_adjuntadas', to=settings.AUTH_USER_MODEL)),
                ('afiliado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financiadores.afiliado')),
                ('convenio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='financiadores.convenio')),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='facturas_registradas', to=settings.AUTH_USER_MODEL)),
                ('financiador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiadores.financiador')),
            ],
            options={
                'ordering': ['-fecha', '-id'],
                'constraints': [models.UniqueConstraint(fields=('financiador', 'clave_duplicado'), name='fin_factura_duplicado'), models.CheckConstraint(condition=models.Q(('importe__gt', 0)), name='fin_factura_importe_positivo')],
            },
        ),
    ]
