# Generated by Django 5.2.15 on 2026-10-06 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128, verbose_name='contraseña')),
                ('email_verificado_at', models.DateTimeField(blank=True, null=True, verbose_name='email verificado')),
                ('activa', models.BooleanField(default=True)),
                ('identidad', models.CharField(choices=[('sin_validar', 'sin validar'), ('validada', 'validada')], default='sin_validar', max_length=12)),
                ('documento', models.CharField(blank=True, max_length=30)),
                ('sexo', models.CharField(blank=True, choices=[('F', 'femenino'), ('M', 'masculino'), ('X', 'X')], max_length=1)),
                ('identidad_via', models.CharField(blank=True, choices=[('renaper', 'RENAPER')], max_length=12, verbose_name='vía de validación')),
                ('identidad_validada_at', models.DateTimeField(blank=True, null=True, verbose_name='identidad validada')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('apellido', models.CharField(blank=True, max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('intentos_validacion', models.PositiveSmallIntegerField(default=0)),
                ('validacion_bloqueada_hasta', models.DateTimeField(blank=True, null=True)),
                ('validacion_en_curso_hasta', models.DateTimeField(blank=True, null=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'cuenta de paciente',
                'verbose_name_plural': 'cuentas de pacientes',
                'constraints': [models.UniqueConstraint(condition=models.Q(('identidad', 'validada')), fields=('documento',), name='portal_documento_validado_unico')],
            },
        ),
        migrations.CreateModel(
            name='EnlacePortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('verificacion', 'verificación de email'), ('recupero', 'recupero de contraseña')], max_length=12)),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('vence', models.DateTimeField()),
                ('usado_at', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='portal.cuentapaciente')),
            ],
            options={
                'verbose_name': 'enlace del portal',
                'verbose_name_plural': 'enlaces del portal',
            },
        ),
        migrations.CreateModel(
            name='EventoPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('alta', 'alta de cuenta'), ('email_verificado', 'email verificado'), ('ingreso', 'ingreso'), ('ingreso_fallido', 'ingreso fallido'), ('contrasena_cambiada', 'contraseña cambiada'), ('contrasena_restablecida', 'contraseña restablecida'), ('identidad_validada', 'identidad validada'), ('identidad_rechazada', 'identidad rechazada por RENAPER'), ('validacion_bloqueada', 'validación bloqueada'), ('documento_en_uso', 'documento validado en otra cuenta'), ('renaper_no_disponible', 'RENAPER no disponible')], max_length=24)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('ip', models.CharField(blank=True, max_length=64)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('momento', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='portal.cuentapaciente')),
            ],
            options={
                'verbose_name': 'evento del portal',
                'verbose_name_plural': 'eventos del portal',
                'ordering': ['-momento'],
            },
        ),
        migrations.CreateModel(
            name='SesionPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acceso_hash', models.CharField(max_length=64, unique=True)),
                ('acceso_vence', models.DateTimeField()),
                ('renovacion_hash', models.CharField(max_length=64, unique=True)),
                ('renovacion_vence', models.DateTimeField()),
                ('vence_maximo', models.DateTimeField()),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('revocada_at', models.DateTimeField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='portal.cuentapaciente')),
            ],
            options={
                'verbose_name': 'sesión del portal',
                'verbose_name_plural': 'sesiones del portal',
            },
        ),
    ]
