# Generated by Django 5.2.15 on 2026-10-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_tabla_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoportal',
            name='tipo',
            field=models.CharField(choices=[('alta', 'alta de cuenta'), ('email_verificado', 'email verificado'), ('ingreso', 'ingreso'), ('ingreso_fallido', 'ingreso fallido'), ('contrasena_cambiada', 'contraseña cambiada'), ('contrasena_restablecida', 'contraseña restablecida'), ('identidad_validada', 'identidad validada'), ('identidad_rechazada', 'identidad rechazada por RENAPER'), ('validacion_bloqueada', 'validación bloqueada'), ('documento_en_uso', 'documento validado en otra cuenta'), ('renaper_no_disponible', 'RENAPER no disponible'), ('descarte_por_nacimiento', 'registro descartado por fecha de nacimiento')], max_length=24),
        ),
    ]
