# Generated by Django 6.0.7 on 2026-08-02 20:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0013_itemfila_turno_a_ticket'),
        ('instituciones', '0008_cama_estadiacama'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('central', models.BooleanField(default=False, verbose_name='es la farmacia central')),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositos', to='instituciones.area')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='instituciones.institucion')),
            ],
            options={
                'verbose_name': 'depósito',
                'verbose_name_plural': 'depósitos',
                'ordering': ['-central', 'nombre'],
                'unique_together': {('institucion', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, help_text='Código interno o de proveedor.', max_length=40)),
                ('nombre', models.CharField(max_length=200)),
                ('generico', models.CharField(blank=True, max_length=200, verbose_name='genérico / droga')),
                ('tipo', models.CharField(choices=[('medicamento', 'Medicamento'), ('descartable', 'Descartable'), ('insumo', 'Insumo general')], default='medicamento', max_length=20)),
                ('presentacion', models.CharField(blank=True, help_text='Ej.: «Ampolla 500 mg».', max_length=120)),
                ('unidad', models.CharField(default='unidad', help_text='Ej.: comprimido, ampolla, ml.', max_length=30)),
                ('requiere_lote', models.BooleanField(default=True, verbose_name='lleva lote y vencimiento')),
                ('controlado', models.BooleanField(default=False, verbose_name='controlado (Ley 19.303)')),
                ('stock_minimo', models.PositiveIntegerField(default=0, verbose_name='stock mínimo')),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='instituciones.institucion')),
            ],
            options={
                'verbose_name': 'insumo',
                'verbose_name_plural': 'insumos',
                'ordering': ['nombre'],
                'unique_together': {('institucion', 'nombre', 'presentacion')},
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=60, verbose_name='número de lote')),
                ('vencimiento', models.DateField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='farmacia.insumo')),
            ],
            options={
                'verbose_name': 'lote',
                'verbose_name_plural': 'lotes',
                'ordering': ['vencimiento', 'numero'],
                'unique_together': {('insumo', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('preparado', 'Preparado'), ('entregado', 'Entregado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('urgente', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('resuelto', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_hechos', to=settings.AUTH_USER_MODEL)),
                ('destino', models.ForeignKey(help_text='Depósito al que se le pide (normalmente la central).', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_recibidos', to='farmacia.deposito')),
                ('origen', models.ForeignKey(help_text='Depósito que pide.', on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_hechos', to='farmacia.deposito')),
            ],
            options={
                'verbose_name': 'pedido de reposición',
                'verbose_name_plural': 'pedidos de reposición',
                'ordering': ['-urgente', 'creado'],
            },
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_cant', models.PositiveIntegerField(verbose_name='cantidad pedida')),
                ('entregado', models.PositiveIntegerField(default=0, verbose_name='cantidad entregada')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas_pedido', to='farmacia.insumo')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='farmacia.pedido')),
            ],
            options={
                'verbose_name': 'línea de pedido',
                'verbose_name_plural': 'líneas de pedido',
                'ordering': ['insumo__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Existencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='farmacia.deposito')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='farmacia.insumo')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='existencias', to='farmacia.lote')),
            ],
            options={
                'verbose_name': 'existencia',
                'verbose_name_plural': 'existencias',
                'ordering': ['insumo__nombre', 'lote__vencimiento'],
                'indexes': [models.Index(fields=['deposito', 'insumo'], name='farmacia_ex_deposit_370515_idx')],
                'unique_together': {('deposito', 'insumo', 'lote')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('consumo', 'Consumo'), ('transferencia', 'Transferencia'), ('ajuste', 'Ajuste de inventario'), ('baja', 'Baja')], max_length=20)),
                ('cantidad', models.PositiveIntegerField()),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_stock', to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='casos.caso')),
                ('destino', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entradas', to='farmacia.deposito')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='farmacia.insumo')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='farmacia.lote')),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='salidas', to='farmacia.deposito')),
            ],
            options={
                'verbose_name': 'movimiento de stock',
                'verbose_name_plural': 'movimientos de stock',
                'ordering': ['-fecha', '-id'],
                'indexes': [models.Index(fields=['insumo', '-fecha'], name='farmacia_mo_insumo__cf7915_idx'), models.Index(fields=['lote'], name='farmacia_mo_lote_id_212b5c_idx')],
            },
        ),
    ]
