# Generated by Django 6.0.6 on 2026-06-23 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('instituciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoCaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('detalle', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'evento de caso',
                'verbose_name_plural': 'eventos de caso',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turno', models.CharField(blank=True, max_length=20)),
                ('urgente', models.BooleanField(default=False)),
                ('orden', models.PositiveIntegerField(default=0)),
                ('atendido', models.BooleanField(default=False)),
                ('ingreso', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'ítem de fila',
                'verbose_name_plural': 'ítems de fila',
                'ordering': ['-urgente', 'orden', 'ingreso'],
            },
        ),
        migrations.CreateModel(
            name='ValorCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(blank=True)),
                ('cargado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'valor de campo',
                'verbose_name_plural': 'valores de campo',
            },
        ),
        migrations.CreateModel(
            name='Caso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('recibido', 'Recibido'), ('en_evaluacion', 'En evaluación'), ('en_espera', 'En espera'), ('derivado', 'Derivado'), ('atendido', 'Atendido'), ('cerrado', 'Cerrado')], default='recibido', max_length=20)),
                ('prioridad', models.CharField(choices=[('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('area_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos', to='instituciones.area')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'caso',
                'verbose_name_plural': 'casos',
                'ordering': ['-creado'],
            },
        ),
    ]
