# Generated by Django 6.0.6 on 2026-06-23 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
        ('flujos', '0001_initial'),
        ('formularios', '0001_initial'),
        ('instituciones', '0001_initial'),
        ('registros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='ciudadano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos', to='registros.ciudadano'),
        ),
        migrations.AddField(
            model_name='caso',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casos', to='instituciones.institucion'),
        ),
        migrations.AddField(
            model_name='caso',
            name='nodo_actual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_en_paso', to='flujos.nodo'),
        ),
        migrations.AddField(
            model_name='caso',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='casos', to='flujos.versionflujo'),
        ),
        migrations.AddField(
            model_name='eventocaso',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventocaso',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='casos.caso'),
        ),
        migrations.AddField(
            model_name='eventocaso',
            name='nodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to='flujos.nodo'),
        ),
        migrations.AddField(
            model_name='itemfila',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='en_filas', to='casos.caso'),
        ),
        migrations.AddField(
            model_name='itemfila',
            name='nodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fila', to='flujos.nodo'),
        ),
        migrations.AddField(
            model_name='valorcampo',
            name='campo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='formularios.campo'),
        ),
        migrations.AddField(
            model_name='valorcampo',
            name='caso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='casos.caso'),
        ),
        migrations.AddField(
            model_name='valorcampo',
            name='nodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valores', to='flujos.nodo'),
        ),
        migrations.AlterUniqueTogether(
            name='valorcampo',
            unique_together={('caso', 'campo')},
        ),
    ]
