# Generated by Django 6.0.6 on 2026-06-24 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivados', to='casos.caso'),
        ),
    ]
