# Generated by Django 6.0.6 on 2026-06-25 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0003_caso_origen'),
        ('instituciones', '0006_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfila',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llamados', to='instituciones.box'),
        ),
    ]
