# Generated by Django 6.0.6 on 2026-06-25 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0004_itemfila_box'),
        ('registros', '0002_estudio_realizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='bloquea_origen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caso',
            name='esperando',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='caso',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='casos_estudio', to='registros.estudio'),
        ),
    ]
