# Generated by Django 6.0.6 on 2026-06-25 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0005_caso_bloquea_origen_caso_esperando_caso_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caso',
            name='estado',
            field=models.CharField(choices=[('recibido', 'Recibido'), ('en_evaluacion', 'En evaluación'), ('en_espera', 'En espera'), ('derivado', 'Derivado'), ('atendido', 'Atendido'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='recibido', max_length=20),
        ),
    ]
