# Generated by Django 6.0.6 on 2026-06-27 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0007_notificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfila',
            name='atendido_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='atención'),
        ),
        migrations.AddField(
            model_name='itemfila',
            name='llamado_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='llamado'),
        ),
    ]
