# Generated by Django 6.0.7 on 2026-08-02 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0009_itemfila_rellamado'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='paso_desde',
            field=models.DateTimeField(blank=True, help_text='Cuándo entró al nodo actual. Base del SLA.', null=True, verbose_name='en este paso desde'),
        ),
        migrations.AddField(
            model_name='caso',
            name='reactivar_en',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Vencimiento de la espera por tiempo. Lo consume `correr_tiempos`.', null=True, verbose_name='reactivar en'),
        ),
        migrations.AddField(
            model_name='caso',
            name='sla_avisado',
            field=models.BooleanField(default=False, verbose_name='ya se avisó la demora'),
        ),
    ]
