# Generated by Django 6.0.7 on 2026-08-02 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0010_caso_paso_desde_caso_reactivar_en_caso_sla_avisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemfila',
            name='ausente',
            field=models.BooleanField(default=False, verbose_name='no se presentó'),
        ),
        migrations.AddField(
            model_name='itemfila',
            name='ausente_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='marcado ausente'),
        ),
    ]
