# Generated by Django 6.0.7 on 2026-08-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0011_itemfila_ausente_itemfila_ausente_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='valorcampo',
            options={'ordering': ['id'], 'verbose_name': 'valor de campo', 'verbose_name_plural': 'valores de campo'},
        ),
    ]
