# Generated by Django 5.2.15 on 2026-09-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0013_itemfila_turno_a_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='caso',
            name='espera_autorizacion',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
