# Generated by Django 6.0.6 on 2026-06-23 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('casos', '0001_initial'),
        ('instituciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=40, verbose_name='código (CIU)')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(blank=True, max_length=120)),
                ('documento', models.CharField(blank=True, max_length=30, verbose_name='documento')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('obra_social', models.CharField(blank=True, max_length=120, verbose_name='obra social')),
                ('domicilio', models.CharField(blank=True, max_length=255)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciudadanos', to='instituciones.institucion')),
            ],
            options={
                'verbose_name': 'ciudadano',
                'verbose_name_plural': 'ciudadanos',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.CharField(blank=True, max_length=255)),
                ('condiciones', models.CharField(blank=True, max_length=255, verbose_name='condiciones / antecedentes')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('ciudadano', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historia_clinica', to='registros.ciudadano')),
            ],
            options={
                'verbose_name': 'historia clínica',
                'verbose_name_plural': 'historias clínicas',
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=150)),
                ('resultado', models.CharField(blank=True, choices=[('normal', 'Normal'), ('alterado', 'Alterado')], max_length=20)),
                ('archivo', models.CharField(blank=True, max_length=255, verbose_name='archivo')),
                ('autor', models.CharField(blank=True, max_length=150)),
                ('fecha', models.DateField()),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estudios', to='registros.historiaclinica')),
            ],
            options={
                'verbose_name': 'estudio',
                'verbose_name_plural': 'estudios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='EntradaHistoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='título')),
                ('contenido', models.TextField(blank=True)),
                ('firmada', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_historia', to=settings.AUTH_USER_MODEL)),
                ('caso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entradas_historia', to='casos.caso')),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entradas', to='registros.historiaclinica')),
            ],
            options={
                'verbose_name': 'entrada de historia clínica',
                'verbose_name_plural': 'entradas de historia clínica',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField()),
                ('activa', models.BooleanField(default=True)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to=settings.AUTH_USER_MODEL)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='registros.historiaclinica')),
            ],
            options={
                'verbose_name': 'receta',
                'verbose_name_plural': 'recetas',
                'ordering': ['-fecha'],
            },
        ),
    ]
