# Generated by Django 6.0.6 on 2026-06-25 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudio',
            name='realizado',
            field=models.BooleanField(default=False, verbose_name='realizado'),
        ),
    ]
