# Generated by Django 6.0.7 on 2026-08-02 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_entradahistoria_matricula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historiaclinica',
            options={'ordering': ['id'], 'verbose_name': 'historia clínica', 'verbose_name_plural': 'historias clínicas'},
        ),
    ]
