# Generated by Django 6.0.7 on 2026-08-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0004_alter_historiaclinica_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradahistoria',
            name='firmada_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='firmada el'),
        ),
        migrations.AddField(
            model_name='entradahistoria',
            name='sello',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
        migrations.AddField(
            model_name='entradahistoria',
            name='sello_previo',
            field=models.CharField(blank=True, editable=False, max_length=64),
        ),
    ]
