# Generated by Django 6.0.7 on 2026-08-14 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        ('registros', '0005_entradahistoria_firmada_at_entradahistoria_sello_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentimientoDatos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otorgado', models.BooleanField(default=True, help_text='False = revocación de un consentimiento anterior.')),
                ('modo', models.CharField(choices=[('escrito', 'Escrito'), ('verbal', 'Verbal'), ('digital', 'Digital')], default='escrito', max_length=20)),
                ('alcance', models.TextField(blank=True, help_text='Para qué se consintió: atención, docencia, investigación…')),
                ('momento', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='registros.ciudadano')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='consentimientos', to='instituciones.institucion')),
                ('tomado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consentimientos_tomados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'consentimiento de datos',
                'verbose_name_plural': 'consentimientos de datos',
                'ordering': ['-momento', '-id'],
            },
        ),
    ]
