# Generated by Django 6.1 on 2026-08-15 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casos', '0013_itemfila_turno_a_ticket'),
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        ('registros', '0006_consentimientodatos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentes_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='antecedentes actualizados el'),
        ),
        migrations.AddField(
            model_name='historiaclinica',
            name='antecedentes_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='antecedentes_cargados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='ciudadano',
            constraint=models.UniqueConstraint(condition=models.Q(('documento', ''), _negated=True), fields=('institucion', 'documento'), name='ciudadano_documento_unico_por_institucion'),
        ),
        migrations.AddConstraint(
            model_name='entradahistoria',
            constraint=models.UniqueConstraint(condition=models.Q(('sello_previo', ''), _negated=True), fields=('historia', 'sello_previo'), name='entrada_un_solo_eslabon_siguiente'),
        ),
    ]
