# Generated by Django 6.0.6 on 2026-08-19 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instituciones', '0009_institucion_latitud_institucion_longitud'),
        ('registros', '0008_normalizar_documentos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruta', models.CharField(max_length=255, unique=True)),
                ('nombre_original', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('tamano', models.PositiveBigIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('proposito', models.CharField(choices=[('adjunto_caso', 'Adjunto de caso'), ('estudio', 'Estudio'), ('otro', 'Otro')], default='adjunto_caso', max_length=30)),
                ('objeto_tipo', models.CharField(blank=True, max_length=80)),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos_clinicos', to='instituciones.institucion')),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos_clinicos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'archivo clinico',
                'verbose_name_plural': 'archivos clinicos',
                'ordering': ['-creado', '-id'],
                'indexes': [models.Index(fields=['institucion', 'creado'], name='registros_a_institu_98f33c_idx'), models.Index(fields=['objeto_tipo', 'objeto_id'], name='registros_a_objeto__b49194_idx')],
            },
        ),
    ]
