# Generated by Django 5.2.15 on 2026-09-17 18:59

from django.db import migrations, models

# La versión con la que se selló todo lo que existe hasta esta migración. Va
# escrita acá y no importada de `integridad.VERSION`: la constante avanza con el
# código y esto tiene que quedar clavado en el valor histórico, si no el backfill
# de mañana escribiría la versión equivocada sobre sellos de ayer.
VERSION_PREVIA = "cauce-sha256-v1"


def marcar_version_previa(apps, schema_editor):
    """
    Lo ya sellado se selló con `cauce-sha256-v1`, antes de que la versión se
    guardara por entrada. Dejarlo en blanco haría que `_canonico` cayera en la
    constante vigente y toda historia firmada se reportaría como adulterada:
    exactamente el falso positivo que el sellado existe para no producir.
    """
    apps.get_model("registros", "EntradaHistoria").objects.exclude(sello="").update(
        sello_version=VERSION_PREVIA
    )


def sin_vuelta_atras(apps, schema_editor):
    """Revertir sólo quita la columna; los sellos no se tocan."""


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0009_archivoclinico'),
    ]

    operations = [
        migrations.AddField(
            model_name='entradahistoria',
            name='sello_version',
            field=models.CharField(blank=True, editable=False, max_length=32),
        ),
        migrations.RunPython(marcar_version_previa, sin_vuelta_atras),
    ]
