# Generated by Django 5.2.15 on 2026-09-24 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0010_sello_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentimientodatos',
            name='consentimiento_referido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='revocaciones', to='registros.consentimientodatos'),
        ),
        migrations.AddField(
            model_name='consentimientodatos',
            name='evidencia',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='consentimiento_datos', to='registros.archivoclinico'),
        ),
        migrations.AddField(
            model_name='consentimientodatos',
            name='motivo_revocacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consentimientodatos',
            name='texto_comunicado',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='consentimientodatos',
            name='version_texto',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='archivoclinico',
            name='proposito',
            field=models.CharField(choices=[('adjunto_caso', 'Adjunto de caso'), ('estudio', 'Estudio'), ('otro', 'Otro'), ('consentimiento', 'Evidencia de consentimiento')], default='adjunto_caso', max_length=30),
        ),
    ]
